export const transactions = [
  {
    icon: "",
    description: "description",
    transactionId: "transaction",
    type: "type",
    card: "card",
    date: "date",
    ammount: "ammount",
    receipt: "reciept",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬇️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
  {
    icon: "⬆️ ",
    description: "Spotify Subscription",
    transactionId: "#121232434",
    type: "Shopping",
    card: "123*****",
    date: "25 Jan, 12.30 AM",
    ammount: "+$75",
    receipt: "button",
  },
];

export const lastTransaction = [
  {
    icon: "▶️",
    name: {
      name: "Spotify Subscription",
      date: new Date().toLocaleTimeString(),
    },
    type: "Shopping",
    account: "1234 ****",
    status: "pending",
    balance: "-$150",
  },
  {
    icon: "⚓",
    name: {
      name: "Spotify Subscription",
      date: new Date().toLocaleTimeString(),
    },
    type: "Shopping",
    account: "1234 ****",
    status: "pending",
    balance: "-$150",
  },
  {
    icon: "👤",
    name: {
      name: "Spotify Subscription",
      date: new Date().toLocaleTimeString(),
    },
    type: "Shopping",
    account: "1234 ****",
    status: "pending",
    balance: "-$150",
  },
];

export const loanOverview = [
  {
    slNo: "slNo",
    loanMoney: "loanMoney",
    leftToReplay: "leftToReplay",
    duration: "duration",
    interestRate: "interestRate",
    installment: "installment",
    button: "Replay",
  },
  {
    slNo: "01",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "02",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "03",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "04",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "05",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "07",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "8 Months",
    interestRate: "12%",
    installment: "$2,00 / month",
    button: "Replay",
  },
  {
    slNo: "Total",
    loanMoney: "&100,000",
    leftToReplay: "$45,00",
    duration: "",
    interestRate: "",
    installment: "$50,000 / month",
    button: "",
  },
];
export const authenticator = [
  { email: "lencholachisa11@gmail.com", password: "123" },
  { email: "l2@gmail.com", password: "123" },
];

export const weeklyActivity = {
  labels: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
  dataset: [
    {
      label: "Diposit",
      data: [480, 350, 320, 480, 160, 395, 400],
      backGroundColor: "blue",
    },
    {
      label: "Withdraw",
      data: [240, 120, 270, 380, 250, 250, 340],
      backGroundColor: "pink",
    },
  ],
};
